4.get/api/reviews
MPlace1/northcoders-project pull request #3
Opened 2022-11-14 15:30 UTC by MPlace1

2022-11-14 16:09 UTC, dav3rid requested changes
Do your tests pass for this one?
I can see that you assert for a comment_count being but I can't see where this gets applied

2022-11-14 16:09 UTC, dav3rid commented on __tests__/app.test.js
> +                    console.log(body)
Can get rid of the log here

2022-11-14 16:09 UTC, dav3rid commented on models/bg.model.js
>              return categories.rows
I would rename this parameter - looks like you've fallen victim to copy paste 😬

2022-11-14 16:09 UTC, dav3rid commented on models/bg.model.js
> +            `select * from reviews`
There will certainly need to be a little more logic here

2022-11-15 09:23 UTC, xViolaine requested changes

2022-11-15 09:23 UTC, xViolaine commented on models/bg.model.js
> +            `select reviews.*, comments.review_id as comment_count from reviews join comments on reviews.review_id = comments.review_id order by reviews.created_at desc`
comment_count is supposed to be the total count of all the comments that correspond with this review_id - you are currently not counting anything, have a look at the COUNT function.

Furthermore, you're using "join" which is essentially an "INNER JOIN". An inner join returns rows when there is a match in both tables. 
This is not the correct choice for the task at hand - have another think about which join we'd want to use here!

2022-11-15 10:10 UTC, xViolaine approved these changes
Good job thinking of the full outer join!

2022-11-15 10:12 UTC, merged